-- CreateTable
CREATE TABLE `digitized_ready` (
    `id` VARCHAR(191) NOT NULL,
    `originalDigitizedId` VARCHAR(191) NOT NULL,
    `companyId` VARCHAR(191) NOT NULL,
    `userId` VARCHAR(191) NOT NULL,
    `originalDocumentId` VARCHAR(191) NOT NULL,
    `fileName` VARCHAR(191) NOT NULL,
    `originalName` VARCHAR(191) NOT NULL,
    `filePath` VARCHAR(191) NOT NULL,
    `fileSize` INTEGER NOT NULL,
    `mimeType` VARCHAR(191) NOT NULL,
    `purchaseDate` DATETIME(3) NULL,
    `vendorName` VARCHAR(191) NULL,
    `vendorAbn` VARCHAR(191) NULL,
    `vendorAddress` VARCHAR(191) NULL,
    `documentType` VARCHAR(191) NULL,
    `receiptNumber` VARCHAR(191) NULL,
    `paymentType` VARCHAR(191) NULL,
    `cashOutAmount` DOUBLE NULL,
    `discountAmount` DOUBLE NULL,
    `amountExclTax` DOUBLE NULL,
    `taxAmount` DOUBLE NULL,
    `totalAmount` DOUBLE NULL,
    `totalPaidAmount` DOUBLE NULL,
    `expenseCategory` VARCHAR(191) NULL,
    `taxStatus` VARCHAR(191) NULL,
    `movedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `digitized_ready_originalDigitizedId_key`(`originalDigitizedId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
